# Generated by Django 4.1.4 on 2023-02-17 09:50

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subTitle', models.CharField(max_length=120)),
                ('blog_image', models.ImageField(upload_to='media')),
                ('content', tinymce.models.HTMLField()),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
