# Generated by Django 4.1.4 on 2023-02-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='coment_body',
            new_name='comment_body',
        ),
    ]
